path:
  train_path: ../dataset/train/train_final.csv
  dev_path: ../dataset/train/train_final.csv
  test_path: ../dataset/test/test_data.csv

model:
  model_name: klue/bert-base

train:
  epochs: 20
  batch_size: 16
  learning_rate: 5e-5
  save_steps: 500
  warmup_steps: 500
  weight_decay: 0.01
  logging_steps: 100
  eval_steps: 500

utils:
  seed: 42
  top_k : 5

wandb:
  project_name: level2_RE
  version_name: 1.1.1 (0.1.0 수정)

use_entity_marker: True

dup_preprocessing: True