path:
  train_path: ../dataset/train/train_final.csv
  dev_path: ../dataset/train/dev_final.csv
  test_path: ../dataset/test/test_final.csv

model:
  model_name: klue/roberta-large

train:
  epochs: 5
  batch_size: 64
  learning_rate: 1e-5
  save_steps: 1000
  warmup_steps: 1000
  weight_decay: 0.01
  logging_steps: 1000
  eval_steps: 1000

utils:
  seed: 42
  top_k : 5

wandb:
  project_name: rlarlgh96